exports.API_NAMESPACE = 'EDENRED_API';

exports.CURRENCY_PRICE_NAMESPACE = 'CURRENCY_PRICES';

exports.CURRENCY_CACHE_KEY = 'CURRENCY';

exports.DEFAULT_CURRENCY = 'ARS';

exports.AVAILABLE_CURRENCIES = ['CLP', 'USD'];
