exports.API_NAMESPACE = 'EDENRED_API';

exports.CURRENCY_PRICE_NAMESPACE = 'CURRENCY_PRICES';

exports.CURRENCY_CACHE_KEY = 'CURRENCY';

exports.BALANCE_CACHE_KEY = 'BALANCE';

exports.CURRENCY_BASE = 'ARS';

exports.AVAILABLE_CURRENCIES = ['CLP', 'MXN', 'COP', 'BRL', 'PEN'];

exports.CURRENCY_SOURCE = 'USD';
